init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

matrix:
  allow_failures:
    - nodejs_version: "0.11"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - ps: 'npm test #PowerShell'
  - cmd: npm test

cache:
  - node_modules
